### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by stoneminer02** [SpigotSuite/SpigotSuite#5]
net.spigotsuite is a bad naming for a package, due spigotsuite.net is not registered.3

**Comment by Plusgames** [comment]
Will be looked up
Please stand by

**Comment by Plusgames** [comment]
Will be changed to spigotsuite.github.io

Its reserved under this Organization @SpigotSuite
[](http://spigotsuite.github.io/)

**Comment by Plusgames** [comment]
Was fixed with last Commit
